Added Fortran related support, added new fortran linktest example, added support for linktests for C and Fotran.

diff --git a/src/mpe2/src/collchk/test/Makefile.in b/src/mpe2/src/collchk/test/Makefile.in
--- a/src/mpe2/src/collchk/test/Makefile.in
+++ b/src/mpe2/src/collchk/test/Makefile.in
@@ -1,54 +1,68 @@
 
 ##### User configurable options #####
 
-MAKE          = @MAKE@
+MAKE                 = @MAKE@
 
-MPI_CC        = @MPI_CC@
-MPI_CLINKER   = $(MPI_CC)
+MPI_CC               = @MPI_CC@
+MPI_F77              = @MPI_F77@
+MPI_CLINKER          = $(MPI_CC)
+MPI_FLINKER          = $(MPI_F77)
 
-DEBUG_LIBS    = @DEBUG_LIBS@
-MPI_INC       = @MPI_INC@
-MPI_LIBS      = @MPI_LIBS@
-CFLAGS        = @CFLAGS@
-MPE_INCDIR    = @includebuild_dir@
-MPE_LIBDIR    = @libbuild_dir@
-COLLCHK_LIBS  = -L$(MPE_LIBDIR) @COLLCHK_LIBS@
+DEBUG_LIBS           = @DEBUG_LIBS@
+MPI_INC              = @MPI_INC@
+MPI_LIBS             = @MPI_LIBS@
+CFLAGS               = @CFLAGS@
+FFLAGS               = @FFLAGS@
+MPE_INCDIR           = @includebuild_dir@
+MPE_LIBDIR           = @libbuild_dir@
+F2CMPI_LIBS          = @F2CMPI_LIBS@
+COLLCHK_LIBS         = -L$(MPE_LIBDIR) @COLLCHK_LIBS@ $(MPI_LIBS)
+COLLCHK_FLIBS        = @FLIB_PATH_LEADER@$(MPE_LIBDIR) \
+                       $(F2CMPI_LIBS) @COLLCHK_LIBS@ \
+                       $(MPI_LIBS)
 
-C_INCS        = -I$(MPE_INCDIR) $(MPI_INC)
-RM            = @RM@
+C_INCS               = -I$(MPE_INCDIR) $(MPI_INC)
+F_INCS               = @FINC_PATH_LEADER@$(MPE_INCDIR) $(MPI_INC)
+LDFLAGS              = @LDFLAGS@
+MPE_BUILD_FORTRAN2C  = @MPE_BUILD_FORTRAN2C@
+RM                   = @RM@
 
 #### End User configurable options ###
 
 srcdir        = @srcdir@
 
 CC_FLAGS      = $(CFLAGS) $(C_INCS) $(MPE_COPTS)
+FC_FLAGS      = $(FFLAGS) $(F_INCS) $(MPE_FOPTS)
 CC_LDFLAGS    = $(LDFLAGS) $(CFLAGS) $(MPE_LDOPTS)
+FC_LDFLAGS    = $(LDFLAGS) $(FFLAGS) $(MPE_LDOPTS)
 
 @VPATH@
 
-.SUFFIXES: .c .@OBJEXT@ @EXEEXT@
+.SUFFIXES: .c .f .@OBJEXT@ @EXEEXT@
 
-SRC           = wrong_composite.c wrong_scatterv.c \
+C_SRC         = wrong_composite.c wrong_scatterv.c \
                 wrong_int_byte.c wrong_root.c \
                 composite.c scatterv.c \
                 time_bcast.c time_allreduce.c \
                 time_alltoallv.c time_alltoallv0.c
-OBJS          = $(SRC:.c=.@OBJEXT@)
-EXECS         = $(OBJS:.o=)
+F_SRC         = fwrong_int_byte.f
+C_OBJS        = $(C_SRC:.c=.@OBJEXT@)
+F_OBJS        = $(F_SRC:.f=.@OBJEXT@)
+C_EXECS       = $(C_OBJS:.o=)
 
-OPT_EXECS     = time_bcast_nochk@EXEEXT@ time_allreduce_nochk@EXEEXT@ \
+OPT_C_EXECS   = time_bcast_nochk@EXEEXT@ time_allreduce_nochk@EXEEXT@ \
                 time_alltoallv0_nochk@EXEEXT@ time_alltoallv_nochk@EXEEXT@
+
+OPT_F_EXECS   = fwrong_int_byte@EXEEXT@ fwrong_int_byte_nochk@EXEEXT@
 
 .c.@OBJEXT@:
 	$(MPI_CC) $(CC_FLAGS) -c $<
 
+.f.@OBJEXT@:
+	$(MPI_F77) $(FC_FLAGS) -c $<
+
 .@OBJEXT@@EXEEXT@:
-	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $< $(COLLCHK_LIBS) $(MPI_LIBS)
-
-default: $(OBJS) $(EXECS) $(OPT_EXECS)
-
-clean:
-	@-$(RM) -f $(EXECS) $(OPT_EXECS) $(OBJS) *.@OBJEXT@
+	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $< $(COLLCHK_LIBS)
 
 time_bcast_nochk@EXEEXT@: time_bcast.@OBJEXT@
 	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $? $(MPI_LIBS)
@@ -61,6 +75,48 @@ time_alltoallv_nochk@EXEEXT@: time_alltoallv.@OBJEXT@
 
 time_alltoallv0_nochk@EXEEXT@: time_alltoallv0.@OBJEXT@
 	$(MPI_CLINKER) $(CC_LDFLAGS) -o $@ $? $(MPI_LIBS)
+
+fwrong_int_byte@EXEEXT@: fwrong_int_byte.@OBJEXT@
+	$(MPI_FLINKER) $(FC_LDFLAGS) -o $@ $? $(COLLCHK_FLIBS)
+
+fwrong_int_byte_nochk@EXEEXT@: fwrong_int_byte.@OBJEXT@
+	$(MPI_FLINKER) $(FC_LDFLAGS) -o $@ $? $(MPI_LIBS)
+
+default: $(C_OBJS) $(C_EXECS) $(OPT_C_EXECS)
+
+linktest: linktest_C
+
+linktest_C:
+	@-echo ; \
+	echo "** Testing if C program can be linked with MPI collective and datatype checking library..." ; \
+	$(RM) -f wrong_int_byte@EXEEXT@ ; \
+	$(MAKE) wrong_int_byte@EXEEXT@ ; \
+	if test -x wrong_int_byte@EXEEXT@ ; then \
+	    echo "** C program can be linked with MPI collective and datatype checking library." ; \
+	    $(RM) -f wrong_int_byte@EXEEXT@ ; \
+	else \
+	    echo "** C program CANNOT be linked with MPI collective and datatype checking library." ; \
+	fi
+
+linktest_F77:
+	@-if [ "$(MPE_BUILD_FORTRAN2C)" = "yes" ] ; then \
+	    echo ; \
+	    echo "** Testing if Fortran77 program can be linked with MPI collective and datatype checking library..." ; \
+	    $(RM) -f fwrong_int_byte@EXEEXT@ ; \
+	    $(MAKE) fwrong_int_byte@EXEEXT@ ; \
+	    if test -x fwrong_int_byte@EXEEXT@ ; then \
+	        echo "** Fortran77 program can be linked with MPI collective and datatype checking library." ; \
+	        $(RM) -f fwrong_int_byte@EXEEXT@ ; \
+	    else \
+	        echo "** Fortran77 program CANNOT be linked with MPI collective and datatype checking library." ; \
+	    fi ; \
+	    echo ; \
+	    $(MAKE) clean ; \
+	  fi
+
+clean:
+	@-$(RM) -f $(C_OBJS) $(F_OBJS) *.@OBJEXT@
+	@-$(RM) -f $(C_EXECS) $(OPT_C_EXECS) $(OPT_F_EXECS)
 
 distclean: clean
 	@-$(RM) -f Makefile
