added low overhead process locks for SPARC v8

diff --git a/src/mpid/ch3/channels/ib/setup_channel b/src/mpid/ch3/channels/ib/setup_channel
--- a/src/mpid/ch3/channels/ib/setup_channel
+++ b/src/mpid/ch3/channels/ib/setup_channel
@@ -27,6 +27,7 @@ fi
 
 pathlist=""
 pathlist="$pathlist src/mpid/${device_name}/channels/${channel_name}/include"
+pathlist="$pathlist src/mpid/common/locks"
 for path in $pathlist ; do
     CPPFLAGS="$CPPFLAGS -I`pwd`/${path}"
     CPPFLAGS="$CPPFLAGS -I${master_top_srcdir}/${path}"
@@ -52,3 +53,14 @@ fi
 #
 #LDFLAGS="$LDFLAGS -L/usr/mellanox/lib"
 #LIBS="$LIBS -lvapi"
+
+dir=${master_top_srcdir}/src/mpid/common/locks
+if test ! -d $dir ; then
+    echo "ERROR: ${dir} does not exist"
+    exit 1
+fi
+file=${dir}/setup
+if test -f $file ; then
+    echo sourcing $file
+    . $file
+fi
diff --git a/src/mpid/ch3/channels/sshm/setup_channel b/src/mpid/ch3/channels/sshm/setup_channel
--- a/src/mpid/ch3/channels/sshm/setup_channel
+++ b/src/mpid/ch3/channels/sshm/setup_channel
@@ -19,6 +19,7 @@ echo "RUNNING SETUP_CHANNEL FOR THE SCALABLE-SHARED_MEMORY CHANNEL"
 
 pathlist=""
 pathlist="$pathlist src/mpid/${device_name}/channels/${channel_name}/include"
+pathlist="$pathlist src/mpid/common/locks"
 for path in $pathlist ; do
     CPPFLAGS="$CPPFLAGS -I${master_top_builddir}/${path}"
     CPPFLAGS="$CPPFLAGS -I${master_top_srcdir}/${path}"
@@ -26,3 +27,14 @@ done
 
 devsubsystems="$devsubsystems src/mpid/common/locks"
 CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS"
+
+dir=${master_top_srcdir}/src/mpid/common/locks
+if test ! -d $dir ; then
+    echo "ERROR: ${dir} does not exist"
+    exit 1
+fi
+file=${dir}/setup
+if test -f $file ; then
+    echo sourcing $file
+    . $file
+fi
diff --git a/src/mpid/ch3/channels/ssm/setup_channel b/src/mpid/ch3/channels/ssm/setup_channel
--- a/src/mpid/ch3/channels/ssm/setup_channel
+++ b/src/mpid/ch3/channels/ssm/setup_channel
@@ -19,6 +19,7 @@ echo "RUNNING SETUP_CHANNEL FOR THE SOCK-SHARED_MEMORY CHANNEL"
 
 pathlist=""
 pathlist="$pathlist src/mpid/${device_name}/channels/${channel_name}/include"
+pathlist="$pathlist src/mpid/common/locks"
 for path in $pathlist ; do
     CPPFLAGS="$CPPFLAGS -I${master_top_builddir}/${path}"
     CPPFLAGS="$CPPFLAGS -I${master_top_srcdir}/${path}"
@@ -33,5 +34,16 @@ CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS"
 file=${master_top_srcdir}/src/mpid/common/sock/setup
 if test -f $file ; then
     echo "sourcing $file"
+    . $file
+fi
+
+dir=${master_top_srcdir}/src/mpid/common/locks
+if test ! -d $dir ; then
+    echo "ERROR: ${dir} does not exist"
+    exit 1
+fi
+file=${dir}/setup
+if test -f $file ; then
+    echo sourcing $file
     . $file
 fi
