Added sbin/mpetestexec to do simple mpiexec testrun, sbin/mpetestexeclog to do mpiexec testrun and then clog2TOslog2 conversion test.  Added sbin/mpecheckbuild to provide support of "make check" in build_dir and sbin/mpecheckinstall to provide support of "make installcheck-all" in install_dir.  Where sbin/mpecheckinstall replaces/simplifies sbin/mpeinstallcheck.  Modified sbin/mpeinstall to install the new sbin/mpetest* and sbin/mpecheckinstall to the install_dir so user can run full installation tests without depending on the build_dir.

diff --git a/src/mpe2/sbin/mpetestexec.in b/src/mpe2/sbin/mpetestexec.in
--- a/src/mpe2/sbin/mpetestexec.in
+++ b/src/mpe2/sbin/mpetestexec.in
@@ -9,8 +9,10 @@ ECHO_C="@ECHO_C@"
 ECHO_T="@ECHO_T@"
 RM="@RM@"
 
+execdirname=`dirname $0`
 execbasename=`basename $0`
 MPE_OUTFILE="mpe2_${execbasename}.txt"
+MPERUN=${MPERUN:-"$execdirname/../bin/mpiexec -n 4"}
 
 pgm=$1
 message=$2
@@ -20,7 +22,17 @@ echo ${ECHO_N} "$message ${ECHO_C}"
 $RM -f $pgm
 $MAKE $pgm > $MPE_OUTFILE 2>&1
 if [ -x $pgm ] ; then
-    echo "${ECHO_T}Yes."
+    $RM -f $MPE_OUTFILE
+    echo "$MPERUN $pgm" > $MPE_OUTFILE
+    $MPERUN $pgm >> $MPE_OUTFILE 2>&1
+    mperun_rc=$?
+    if [ $mperun_rc != 0 ] ; then
+        echo "${ECHO_T}No."
+        echo "    The failed command is :"
+        cat $MPE_OUTFILE 
+    else
+        echo "${ECHO_T}Yes."
+    fi
     $RM -f $pgm
 else
     echo "${ECHO_T}No."
