MPI2 requires that the sized types (e.g., MPI_INTEGER2) be distinct from other predefined types.  Changed the f77 configure to make them distinct

diff --git a/src/binding/f77/configure.in b/src/binding/f77/configure.in
--- a/src/binding/f77/configure.in
+++ b/src/binding/f77/configure.in
@@ -3,6 +3,7 @@ dnl This has been derived from the MPICH-1 configure for the Fortran
 dnl binding.  It still needs major editing.
 dnl
 AC_INIT(Makefile.in)
+use_alias_types=no
 dnl
 dnl Cygwin uses PREREQ to decide which autoconf/autoheader to run.  
 dnl It does not do this correctly, since it compares against 2.13 but
@@ -744,51 +745,71 @@ float_mpi=${MPI_FLOAT:-0}
 double_mpi=${MPI_DOUBLE:-0}
 long_double_mpi=${MPI_LONG_DOUBLE:-0}
 
-for len in 1 2 4 8 16 ; do
-    eval F77_INTEGER$len=0
-    #eval testval=\$"pac_cv_f77_sizeof_integer_$len"
-    eval testval=\$"has_integer_$len"
-    if test "$testval" = 0 ; then continue ; fi
-    noval="yes"
-    AC_MSG_CHECKING([for C type matching Fortran integer*$len])
-    for c_type in char short int long "long_long" ; do
-	eval ctypelen=\$"ac_cv_sizeof_$c_type"
-	if test "$testval" = "$ctypelen" -a "$ctypelen" -gt 0 ; then
-	    AC_MSG_RESULT($c_type)
-	    eval F77_INTEGER$len=\$"${c_type}_mpi"
-	    noval="no"
-	    break
+#
+# The following code was correct for MPI-1, which allowed these datatypes
+# to be an alias for another MPI type.  MPI-2 requires these to 
+# be distinct types, so these are enumerated
+if test "$use_alias_types" = yes ; then
+    for len in 1 2 4 8 16 ; do
+        eval F77_INTEGER$len=0
+        #eval testval=\$"pac_cv_f77_sizeof_integer_$len"
+        eval testval=\$"has_integer_$len"
+        if test "$testval" = 0 ; then continue ; fi
+        noval="yes"
+        AC_MSG_CHECKING([for C type matching Fortran integer*$len])
+        for c_type in char short int long "long_long" ; do
+	    eval ctypelen=\$"ac_cv_sizeof_$c_type"
+  	    if test "$testval" = "$ctypelen" -a "$ctypelen" -gt 0 ; then
+	        AC_MSG_RESULT($c_type)
+	        eval F77_INTEGER$len=\$"${c_type}_mpi"
+	        noval="no"
+	        break
+            fi
+        done
+        if test "$noval" = "yes" ; then
+            AC_MSG_RESULT([unavailable])
         fi
     done
-    if test "$noval" = "yes" ; then
-        AC_MSG_RESULT([unavailable])
-    fi
-done
 
-# Complex is set separately above
-for len in 4 8 16 ; do
-    len2=`expr $len + $len`
-    eval F77_REAL$len=0
-    #eval F77_COMPLEX$len2=0
-    #eval testval=\$"pac_cv_f77_sizeof_real_$len"
-    eval testval=\$"has_real_$len"
-    if test "$testval" = 0 ; then continue ; fi
-    noval="yes"
-    AC_MSG_CHECKING([for C type matching Fortran real*$len])
-    for c_type in float double "long_double" ; do
-	eval ctypelen=\$"ac_cv_sizeof_$c_type"
-	if test "$testval" = "$ctypelen" -a "$ctypelen" -gt 0 ; then
-	    AC_MSG_RESULT($c_type)
-	    eval F77_REAL$len=\$"${c_type}_mpi"
-	    #eval F77_COMPLEX$len2=\$"${c_type}_cplx_mpi"
-            noval="no"
-	    break
+    # Complex is set separately above
+    for len in 4 8 16 ; do
+        len2=`expr $len + $len`
+        eval F77_REAL$len=0
+        #eval F77_COMPLEX$len2=0
+        #eval testval=\$"pac_cv_f77_sizeof_real_$len"
+        eval testval=\$"has_real_$len"
+        if test "$testval" = 0 ; then continue ; fi
+        noval="yes"
+        AC_MSG_CHECKING([for C type matching Fortran real*$len])
+        for c_type in float double "long_double" ; do
+	    eval ctypelen=\$"ac_cv_sizeof_$c_type"
+	    if test "$testval" = "$ctypelen" -a "$ctypelen" -gt 0 ; then
+	        AC_MSG_RESULT($c_type)
+	        eval F77_REAL$len=\$"${c_type}_mpi"
+	        #eval F77_COMPLEX$len2=\$"${c_type}_cplx_mpi"
+                noval="no"
+	        break
+            fi
+        done
+        if test "$noval" = "yes" ; then
+            AC_MSG_RESULT([unavailable])
         fi
     done
-    if test "$noval" = "yes" ; then
-        AC_MSG_RESULT([unavailable])
-    fi
-done
+else 
+   # Simply determine which types exist.  These may have been set by the
+   # toplevel configure
+   for var in INTEGER1 INTEGER2 INTEGER4 INTEGER8 INTEGER16 \
+        REAL4 REAL8 REAL16 COMPLEX8 COMPLEX16 COMPLEX32 ; do  
+	eval varname=MPI_$var
+        eval varvalue=\$$varname
+	echo "$varname = $varvalue"
+	if test "$varvalue" = MPI_DATATYPE_NULL ; then
+	    eval F77_$var=0
+	else
+  	    eval F77_$var=\$$varname
+	fi
+   done
+fi
 # We must convert all hex values to decimal (!)
 for var in INTEGER1 INTEGER2 INTEGER4 INTEGER8 INTEGER16 \
     REAL4 REAL8 REAL16 COMPLEX8 COMPLEX16 COMPLEX32 ; do  
@@ -805,6 +826,20 @@ for var in INTEGER1 INTEGER2 INTEGER4 INTEGER8 INTEGER16 \
     for pos in 3 4 5 6 7 8 9 10 ; do
         #char=`expr substr $fullvarvalue $pos 1`
         char=`expr $fullvarvalue : '\(.\)'`
+	# We don't test for success of expr here because some expr's are
+	# buggy and set the status to one on expressions like
+        #    expr 00ccc : '\(.\)'
+        # while both
+        #    expr 00ccc : '\(..\)' 
+        # and
+        #    expr 100cc : '\(.\)'
+        # return a zero status.  So the status is set even on success,
+        # if the result is a single character that is a zero (!)
+	#rc=$?
+	#if test "$rc" != 0 ; then
+	dnl #    AC_MSG_WARN([Failure (status $rc) in extracting first char from $fullvarvalue])
+	#    break
+	#fi
 	fullvarvalue=`echo $fullvarvalue | sed -e 's/.\(.*\)/\1/'`
         case $char in 
             a) char=10 ;;
@@ -815,6 +850,9 @@ for var in INTEGER1 INTEGER2 INTEGER4 INTEGER8 INTEGER16 \
 	    f) char=15 ;;
         esac
         value=`expr $value \* 16 + $char`
+	if test $? != 0 ; then
+	    AC_MSG_WARN([Failure to evaluate $value \* 16 + $char])
+	fi
     done
     #echo "$fullvar = $value"
     eval $fullvar=$value
