Updated compilation scripts

diff --git a/src/binding/f77/mpif77.in b/src/binding/f77/mpif77.in
--- a/src/binding/f77/mpif77.in
+++ b/src/binding/f77/mpif77.in
@@ -22,8 +22,11 @@
 #
 # Special issues with shared libraries - todo
 #
+# --------------------------------------------------------------------------
+# Set the default values of all variables.
 #
 # Directory locations: Fixed for any MPI implementation
+# Set from the directory arguments to configure (e.g., --prefix=/usr/local)
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 sysconfdir=@sysconfdir@
@@ -31,6 +34,8 @@ includedir=@includedir@
 libdir=@libdir@
 #
 # Default settings for compiler, flags, and libraries
+# Determined by a combination of environment variables and tests within
+# configure (e.g., determining whehter -lsocket is needee)
 FC="@FC@"
 F77CPP="@F77CPP@"
 MPI_FFLAGS="@MPI_FFLAGS@"
@@ -38,27 +43,131 @@ MPI_LDFLAGS="@MPI_LDFLAGS@"
 MPILIBNAME="@MPILIBNAME@"
 MPI_OTHERLIBS="@LIBS@"
 #
-mpilibs=-l$MPILIBNAME
+# MPIVERSION is the version of the MPICH2 library that mpif77 is intended for
+MPIVERSION=@MPIVERSION@
 #
-# Concatenate the user flags with the ones needed by MPI
-FFLAGS="$FFLAGS $MPI_FFLAGS"
-LDFLAGS="$LDFLAGS $MPI_LDFLAGS"
+# Internal variables
+# Show is set to echo to cause the compilation command to be echoed instead 
+# of executed.
+Show=eval
+#
+# End of initialization of variables
+#---------------------------------------------------------------------
+# Environment Variables.
+# The environment variables MPICH_F77 may be used to override the 
+# default choices.
+# In addition, if there is a file $sysconfdir/mpif77-$F77name.conf, 
+# where F77name is the name of the compiler with all spaces replaced by hyphens
+# (e.g., "cc -64" becomes "cc--64", that file is sources, allowing other
+# changes to the compilation environment.  See the variables used by the 
+# script (defined above)
+if [ -n "$MPICH_F77" ] ; then
+    FC="$MPICH_F77"
+    F77name=`echo $FC | sed 's/ /-/g'`
+    if [ -s $sysconfdir/mpif77-$F77name.conf ] ; then
+        . $sysconfdir/mpif77-$F77name.conf
+    fi
+fi
+#
+# ------------------------------------------------------------------------
+# Argument processing.
+# This is somewhat awkward because of the handling of arguments within
+# the shell.  We want to handle arguments that include spaces without 
+# loosing the spacing (an alternative would be to use a more powerful
+# scripting language that would allow us to retain the array of values, 
+# which the basic (rather than enhanced) Bourne shell does not.  
 #
 # Look through the arguments for arguments that indicate compile only.
 # If these are *not* found, add the library options
+
 linking=yes
+allargs=""
 for arg in "$@" ; do
+    # Set addarg to no if this arg should be ignored by the C compiler
+    addarg=yes
+    qarg=$arg
     case $arg in 
-    -c|-S|-E|-M)
+ 	# ----------------------------------------------------------------
+	# Compiler options that affect whether we are linking or no
+    -c|-S|-E|-M|-MM)
+    # The compiler links by default
     linking=no
     ;;
+	# ----------------------------------------------------------------
+	# Options that control how we use mpif77 (e.g., -show, 
+	# -cc=* -config=*
+    -echo)
+    addarg=no
+    set -x
+    ;;
+
+    -f77=*)
+    FC=`echo A$arg | sed -e 's/A-f77=//g'`
+    addarg=no
+    ;;
+    -fc=*)
+    FC=`echo A$arg | sed -e 's/A-fc=//g'`
+    addarg=no
+    ;;
+
+    -show)
+    addarg=no
+    Show=echo
+    ;;
+    -config=*)
+    addarg=no
+    F77name=`echo A$arg | sed -e 's/A-config=//g'`
+    if [ -s "$sysconfdir/mpif77-$F77name.conf" ] ; then
+        . "$sysconfdir/mpif77-$F77name.conf"
+    else
+	echo "Configuration file mpif77-$F77name.conf not found"
+    fi
+    ;;
+    -compile_info)
+    Show=echo
+    addarg=no
+    ;;
+    -link_info)
+    Show=echo
+    addarg=no
+    ;;
+    -v)
+    # Pass this argument to the compiler as well.
+    echo "mpif77 for $MPIVERSION"
+    ;;
+	# -help
+    -help)
+    ;;
+        # -----------------------------------------------------------------
+	# Other arguments.  We are careful to handle arguments with 
+	# quotes (we try to quote all arguments in case they include 
+	# any spaces)
+    *\"*) 
+    qarg="'"$arg"'"
+    case $arg in 
+       -D*)
+       cppflags="$cppflags $qarg"
+       ;;
     esac
-done
-#
-# A temporary statement to invoke the compiler
-# Place the -L before any args incase there are any mpi libraries in there.
-# Eventually, we'll want to move this after any non-MPI implementation 
-# libraries
+    ;;
+    *\'*) 
+    qarg='\"'"$arg"'\"'
+    case $arg in 
+       -D*)
+       cppflags="$cppflags $qarg"
+       ;;
+    esac
+    ;;
+
+    # The following are special args used to handle .F files when the
+    # Fortran compiler itself does not handle these options
+    -I*)
+    cppflags="$cppflags $arg"
+    ;;
+    -D*)
+    cppflags="$cppflags $arg"
+    ;;
+    *.F|*.F90)
 # If F77CPP is not empty, then we need to do the following:
 #    If any input files have the .F or .F90 extension, then    
 #        If F77CPP = false, then
@@ -68,60 +177,58 @@ done
 #            Replace the input file with this name in the args
 # This is needed only for very broken systems
 #     
-rmfiles=""
-cppflags=""
-if [ -n "$F77CPP" ] ; then
-    count=1
-    allargs=""
-    TMPDIR=${TMPDIR:-/tmp}
-    # FIXME: does not handle spaces or misbalanced quotes
-    for arg in "$@" ; do
-        case $arg in
-	    -I*)
-	    cppflags="$cppflags $arg"
-	    allargs="$allargs $arg"
-	    ;;
-	    -D*)
-	    cppflags="$cppflags $arg"
-	    allargs="$allargs $arg"
-	    ;;
-	    -*)
-	    allargs="$allargs $arg"
-	    ;;
-	    *.F|*.F90)
-	    if [ "$F77CPP" = "false" ] ; then
-	        echo "This Fortran compiler does not accept .F or .F90 files"
-		exit 1
-	    fi
-	    bfile=`basename $arg .F`
-	    tmpfile=$TMPDIR/f$$-$bfile.f
-	    if $F77CPP $cppflags $arg > $tmpfile ; then
-	        # Add this file to the commandline list
-		count=`expr $count + 1`
-		allargs="$allargs $tmpfile"
-		rmfiles="$rmfiles $tmpfile"
-	    else
-		echo "Aborting compilation"
-		exit 1
-	    fi
-	    ;;
-	    *)
-	    allargs="$allargs $arg"
-	    ;;
-	esac
-    done      
-    # Reset the parameter list.  The "--" is a fence that allows the
-    # arguments to be reset from allargs, even for those arguments
-    # that start with a dash.
-    set -- $allargs 
-fi
+    if [ -n "$F77CPP" ] ; then
+        if [ "$F77CPP" = "false" ] ; then
+            echo "This Fortran compiler does not accept .F or .F90 files"
+	    exit 1
+        fi
+        addarg=no
+        bfile=`basename $arg .F`
+        tmpfile=$TMPDIR/f$$-$bfile.f
+        if $F77CPP $cppflags $arg > $tmpfile ; then
+            # Add this file to the commandline list
+	    count=`expr $count + 1`
+	    allargs="$allargs $tmpfile"
+	    rmfiles="$rmfiles $tmpfile"
+        else
+	    echo "Aborting compilation because of failure in preprocessing step"
+	    echo "for file $arg ."
+	    exit 1
+        fi
+    fi
+    # Otherwise, just accept the argument
+    ;;
+    # - end of special handling for .F files
+    
+    *)
+    ;;
+
+    esac
+    if [ $addarg = yes ] ; then
+        allargs="$allargs $qarg"
+    fi
+done
+
+# -----------------------------------------------------------------------
+# Derived variables.  These are assembled from variables set from the
+# default, environment, configuration file (if any) and command-line
+# options (if any)
+mpilibs=-l$MPILIBNAME
 #
+# Concatenate the user flags with the ones needed by MPI
+FFLAGS="$FFLAGS $MPI_FFLAGS"
+LDFLAGS="$LDFLAGS $MPI_LDFLAGS"
+#
+# A temporary statement to invoke the compiler
+# Place the -L before any args incase there are any mpi libraries in there.
+# Eventually, we'll want to move this after any non-MPI implementation 
+# libraries
 #
 if [ "$linking" = yes ] ; then
-    $FC $FFLAGS $LDFLAGS -I$includedir -L$libdir "$@" $mpilibs $MPI_OTHERLIBS
+    $Show $FC $FFLAGS $LDFLAGS -I$includedir -L$libdir $allargs $mpilibs $MPI_OTHERLIBS
     rc=$?
 else
-    $FC $FFLAGS -I$includedir "$@" 
+    $Show $FC $FFLAGS -I$includedir $allargs
     rc=$?
 fi
 if [ -n "$rmfiles" ] ; then
