incorporated changes made between mpig-dev-t2b-20070808-2 and MPICH2_1_0_6

diff --git a/src/mpid/ch3/channels/ssm/setup_channel b/src/mpid/ch3/channels/ssm/setup_channel
--- a/src/mpid/ch3/channels/ssm/setup_channel
+++ b/src/mpid/ch3/channels/ssm/setup_channel
@@ -45,4 +45,7 @@ file=${dir}/setup
 if test -f $file ; then
     echo sourcing $file
     . $file
+else 
+    echo "Cannot find $file , needed to build process locks"
+    exit 1
 fi
