Updates for the dllchannel.  These fix problems with building in mpid/common/locks (the configure there needed to use MPICH_INCLUDE_DIRS) and in the builddll scripts (which needed to properly set that value before invoking the configure in mpid/common/locks).  The fix further emphasizes the need to refactor the ch3 code to properly modularize (the locks routines are built several times, with *different* include files.  This should be ok because of how those files are used, but it is not robust).

diff --git a/src/mpid/ch3/channels/shm/builddll b/src/mpid/ch3/channels/shm/builddll
--- a/src/mpid/ch3/channels/shm/builddll
+++ b/src/mpid/ch3/channels/shm/builddll
@@ -89,7 +89,20 @@ export MPICH2_INCLUDE_FLAGS
 if [ ! -d $mybuild/src/mpid/common/locks ] ; then 
     mkdir $mybuild/src/mpid/common/locks
 fi
-( CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
+# Note that we also need to run the setup in the locks directory
+locksSetup=$mympich2/src/mpid/common/locks/setup
+if [ ! -f $locksSetup ] ; then 
+    echo "Cannot find $locksSetup , needed to build process locks"
+    exit 1
+fi
+
+( MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/datatype" ; \
+MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/ch3/channels/shm/include" ; \
+MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../ch3/channels/shm/include" ; \
+MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../ch3/include" ; \
+export MPICH2_INCLUDE_FLAGS ; \
+CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
+  . $locksSetup ; \
 cd $mybuild/src/mpid/common/locks && \
     $mympich2/src/mpid/common/locks/configure --enable-sharedlibs=$shlibtype \
     --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )
