Enhanced manyconnect to make sure that the test program exists

diff --git a/test/mpi/manual/manyconnect.in b/test/mpi/manual/manyconnect.in
--- a/test/mpi/manual/manyconnect.in
+++ b/test/mpi/manual/manyconnect.in
@@ -4,6 +4,7 @@ prefix="@prefix@"
 exec_prefix="@exec_prefix@"
 mpiexec="@bindir@/mpiexec"
 starter="$mpiexec -n 1"
+testpgm=testconnect
 
 rm -f $file
 
@@ -13,22 +14,55 @@ nconn=100
 # To avoid problems with listner queues, we pause every blockstart
 # processes
 blockstart=10
+
+# Print help/usage information if requested
+if [ "$1" = "-help" -o "$1" = "-usage" ] ; then
+    echo "$0 [ -singleton ] [ nconn [ testprogram ] ]"
+    exit 0
+fi
+
 if [ "$1" = "-singleton" ] ; then
     starter=eval
     shift
 fi
 if [ -n "$1" ] ; then
     nconn=$1
+    shift
 fi
+if [ -n "$1" ] ; then
+    if [ -x "$1" ] ; then
+	testpgm=$1
+    else 
+        echo "Expected to find an executable program; found $1"
+        exit 1
+    fi
+    shift
+fi
+
+# Make sure that the program is executable
+if [ ! -x "$testpgm" ] ; then
+    # Try to make it
+    echo "Making $testpgm"
+    make $testpgm 
+    if [ $? != 0 ] ; then
+	echo "Failure in make $testpgm"
+	exit 1
+    fi
+    if [ ! -x "$testpgm" ] ; then 
+        echo "The program $testpgm either does not exist or is not executable"
+        exit 1
+    fi
+fi
+
 # Start one and sleep to avoid problems with two processes opening the
 # test-port file for writing
-$starter ./testconnect $file $nconn 1 &
+$starter ./$testpgm $file $nconn 1 &
 sleep 1
 nstarted=2
 blockcount=2
 while [ $nstarted -lt $nconn ] ; do
     #echo "Starting $nstarted"
-    $starter ./testconnect $file $nconn $nstarted &
+    $starter ./$testpgm $file $nconn $nstarted &
     echo "Started process $! (num $nstarted)"
     nstarted=`expr $nstarted + 1`
     blockcount=`expr $blockcount + 1`
@@ -40,5 +74,5 @@ while [ $nstarted -lt $nconn ] ; do
     fi
 done
 #echo "Starting $nstarted"
-$starter ./testconnect $file $nconn $nstarted
+$starter ./$testpgm $file $nconn $nstarted
 wait
