Changes to make ch3:tcp compile again.  The header files and some of the source files include a fair amount of work in progress.  Most of this work is either not in use by checked in files or is explicitly disabled so that the "hellow" test program will compile and run.

diff --git a/src/mpid/ch3/Makefile.sm b/src/mpid/ch3/Makefile.sm
--- a/src/mpid/ch3/Makefile.sm
+++ b/src/mpid/ch3/Makefile.sm
@@ -1,16 +1,43 @@
-SUBDIRS = src channels .
+SUBDIRS = . channels src
 
+#
+# the current directory, "dot", must be listed first in order to have
+# the header files verify before make recurses into the source directory
+# and attempts to build files with a broken header files
+#
 all-local: ../../include/mpidpre.h ../../include/mpidpost.h
 
-../../include/mpidpre.h: include/mpidpre.h
-	@echo "ERROR: src/include/mpidpre.h is out of date." ; \
-	 echo "Run './config.status' followed by 'make clean all'." ; \
-	exit 1
+../../include/mpidpre.h: ${srcdir}/include/mpidpre.h
+	@echo " " ; \
+	 echo "ERROR: src/include/mpidpre.h is out of date." ; \
+	 echo "Running config.status and cleaning build tree." ; \
+	 echo " " ; \
+	 ./config.status && \
+	 cd ../../.. && \
+	 make clean 2>&1 >/dev/null ; \
+	 exit 1
 
-../../include/mpidpost.h: include/mpidpost.h
-	@echo "ERROR: src/include/mpidpost.h is out of date." ; \
-	 echo "Run './config.status' followed by 'make clean all'." ; \
+../../include/mpidpost.h: ${srcdir}/include/mpidpost.h
+	@echo " " ; \
+	 echo "ERROR: src/include/mpidpre.h is out of date." ; \
+	 echo "Running config.status and cleaning build tree." ; \
+	 echo " " ; \
+	 ./config.status && \
+	 cd ../../.. && \
+	 make clean 2>&1 >/dev/null ; \
+	 exit 1
+
+../../include/mpid_datatype.h: ${srcdir}/../common/datatype/mpid_datatype.h
+	@echo " " ; \
+	 echo "ERROR: src/include/mpid_datatype.h is out of date." ; \
+	 echo "Running config.status and cleaning build tree." ; \
+	 echo " " ; \
+	 ./config.status && \
+	 cd ../../.. && \
+	 make clean 2>&1 >/dev/null ; \
 	 exit 1
 
 distclean-local:
 	-rm -f ../../include/mpidpre.h ../../include/mpidpost.h
+	-rm -f ../../include/mpid_datatype.h
+	-rm -f include/mpidi_ch3_conf.h
