Many minor fixes for detection of user errors

diff --git a/src/mpid/ch3/setup_device b/src/mpid/ch3/setup_device
--- a/src/mpid/ch3/setup_device
+++ b/src/mpid/ch3/setup_device
@@ -20,8 +20,9 @@ file=${master_top_srcdir}/src/mpid/${device_name}/setup_device.args
 if test -x ${file} ; then 
     . ${file}
 elif test -f ${file} ; then
-    echo "ERROR: ${file} not is executable"
-    exit 1
+#    echo "ERROR: ${file} not is executable"
+#    exit 1
+    . ${file}
 else
     echo "ERROR: ${file} not found"
     exit 1
