Allow test build to use source directories not in /home

diff --git a/maint/testbuild b/maint/testbuild
--- a/maint/testbuild
+++ b/maint/testbuild
@@ -4,6 +4,14 @@
 # created and then runs it
 # The cb suffix is for "check build"
 srcdir=/home/gropp/projects/mpich2
+if [ ! -d $srcdir ] ; then
+    if [ -d /homes/gropp/projects/mpich2 ] ; then
+        srcdir=/homes/gropp/projects/mpich2
+    else
+        # We'll check for it later, after the args
+        srcdir=
+    fi
+fi
 if [ -z "$tmpdir" ] ; then tmpdir=/sandbox/gropp ; fi
 if [ -z "$rundir" ] ; then rundir=$tmpdir/cb/mpich2 ; fi
 if [ -z "$mpichtestdir" ] ; then mpichtestdir=$tmpdir/cb/mpitest ; fi
@@ -52,7 +60,10 @@ done
 
 # Construct the full outfile name from the dir and file
 outfile="$outdir/$outfile"
-
+if [ ! -d "$srcdir" ] ; then
+    echo "Could not find MPICH2 source dir"
+    exit 1
+fi
 if [ ! -d $rundir ] ; then 
     # Assume that we have mkdir -p
     mkdir -p $rundir
