Added an alternative approach for accessing confdb

diff --git a/maint/updatefiles b/maint/updatefiles
--- a/maint/updatefiles
+++ b/maint/updatefiles
@@ -12,6 +12,11 @@
 # mpich tree.  This is not yet implemented.
 error_summary=""
 acVersion=unknown
+# confdbSrcDir is used for checkouts that were not able to checkout 
+# confdb because they're not members of the Unix group that includes that
+# directory.
+confdbSrcDir=/homes/MPI/testing/mpich2/mpich2/confdb
+#
 # finalStatus records whether there have been problems in updatefiles
 # 1 = warning, 3 = fatal, 2 = reserved for future use, 
 # 0 = no problems detected.
@@ -478,8 +483,26 @@ if [ $do_build_configure = yes ] ; then
         # Before we try to rebuild any configure steps, make sure that 
         # we have the necessary macro definitions
         if [ ! -d confdb -o ! -s confdb/aclocal.m4 ] ; then
-	    echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
-  	    exit 1
+	    # See if we can export a copy of confdb
+	    if [ -d $confdbSrcDir ] ; then
+                cp -rp $confdbSrcDir confdb
+                # Remove the CVS directories
+		if test -d confdb/CVS ; then
+                    (cd confdb && find . -name CVS -print | xargs rm -rf)
+                fi
+            else
+                echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
+  	        exit 1
+            fi
+        elif [ -d confdb -a -d "$confdbSrcDir" -a ! -d confdb/CVS ] ; then
+            # This is a copy; get an up-to-date copy.  We only do 
+	    # this if there is an alternate source, in case this is
+	    # part of the distributed version and not local.
+            cp -rp $confdbSrcDir confdb
+            # Remove the CVS directories
+	    if test -d confdb/CVS ; then
+                (cd confdb && find . -name CVS -print | xargs rm -rf)
+            fi
         fi
 	# Check for out-of-date configures (the dependency handling
 	# isn't 100% accurate, so we use this step as an additional
