*** empty log message ***

diff --git a/maint/updatefiles b/maint/updatefiles
--- a/maint/updatefiles
+++ b/maint/updatefiles
@@ -253,7 +253,11 @@ if [ "$has_unix_find" = "yes" ] ; then
 	    # sed -e '/"\"/d' -e 's/\//g'
 	    # (the first removes case statements on \^M, the second
 	    # removes the \^M from the ac_config_files statement
-	    if grep 'src/Makefile \\ src' configure 2>&1 >/dev/null ; then 
+	    if [ ! -s configure ] ; then 
+		echo "PANIC: Could not make configure from configure.in"
+		echo "In directory `pwd`"
+		exit 1
+	    elif grep 'src/Makefile \\ src' configure 2>&1 >/dev/null ; then 
 		rm -f c.tmp 
 		sed -e '/"\\/d' -e 's/\\//g' configure > c.tmp
 		rm -f configure
