Added partial support for extended F90, including basic module

diff --git a/maint/updatefiles b/maint/updatefiles
--- a/maint/updatefiles
+++ b/maint/updatefiles
@@ -182,9 +182,9 @@ fi
 # Check that you have a working autoconf.  Autoconf 2.57 is not compatible with
 # previous versions of autoconf (!!), even 2.52 (!!!).  
 acVersion=ok
-if test -d .tmp ; then rm -rf .tmp ; fi
-if test -s .tmp ; then rm -f .tmp ; fi
-if test ! -d .tmp ; then
+if [ -d .tmp ] ; then rm -rf .tmp ; fi
+if [ -s .tmp ] ; then rm -f .tmp ; fi
+if [ ! -d .tmp ] ; then
     mkdir .tmp 2>&1 >/dev/null
 fi
 # As of autoconf 2.59, the command line arguments changed (again)
@@ -229,51 +229,41 @@ rm -rf .tmp
 #
 # Create the bindings if necessary 
 if [ $do_bindings = "yes" ] ; then
+    build_f77=no
+    build_f90=no
+    build_cxx=no
     if [ $do_f77 = "yes" ] ; then
         if [ ! -s src/binding/f77/abortf.c ] ; then 
 	    build_f77=yes
-        elif find src/binding/f77 -name 'buildiface' -newer 'src/binding/f77/abortf.c' ; then
+        elif find src/binding/f77 -name 'buildiface' -newer 'src/binding/f77/abortf.c' >/dev/null 2>&1 ; then
 	    build_f77=yes
-        else
-	    build_f77=no
         fi
-    else
-        build_f77=no
+        if [ ! -s src/binding/f90/mpi_base.f90 ] ; then
+ 	    build_f90=yes
+        elif find src/binding/f90 -name 'buildiface' -newer 'src/binding/f90/mpi_base.f90' >/dev/null 2>&1 ; then
+	    build_f90=yes
+        fi
+ 
     fi
 
     if [ $build_f77 = "yes" ] ; then
 	echo "Building Fortran 77 interface"
 	( cd src/binding/f77 && chmod a+x ./buildiface && ./buildiface )
     fi
+    if [ $build_f90 = "yes" ] ; then
+	echo "Building Fortran 90 interface"
+	( cd src/binding/f90 && chmod a+x ./buildiface && ./buildiface )
+    fi
 
     if [ ! -s src/binding/cxx/mpicxx.h ] ; then 
 	build_cxx=yes
-    elif find src/binding/cxx -name 'buildiface' -newer 'src/binding/cxx/mpicxx.h' ; then
+    elif find src/binding/cxx -name 'buildiface' -newer 'src/binding/cxx/mpicxx.h' >/dev/null 2>&1 ; then
 	build_cxx=yes
-    else
-	build_cxx=no
     fi
     if [ $build_cxx = "yes" ] ; then
 	echo "Building C++ interface"
-    #    File code still needs work
-    #    if [ ! -d src/mpi/romio ] ; then
-#	    otherarg="-noromio"
-    #    fi
 	( cd src/binding/cxx && chmod a+x ./buildiface &&
 	  ./buildiface -nosep $otherarg )
-    fi
-
-    if [ ! -s src/binding/f90/mpi.f90 ] ; then
-	build_f90=yes
-    elif find src/binding/f90 -name 'buildiface' -newer 'src/binding/f90/mpi.f90' ; then
-	build_f90=yes
-    else
-	build_f90=no
-    fi
-    if [ $build_f90 = "yes" -a -s src/binding/f90/buildiface ] ; then
-	echo "Building F90 interface"
-	( cd src/binding/f90 && chmod a+x ./buildiface && \
-	    ./buildiface $otherarg)
     fi
 fi
 #
@@ -354,7 +344,7 @@ run_configure=no
 # autom4te*.cache file; since this cache is not accurate, we delete it.
 if [ ! -x maint/configure ] ; then
     (cd maint && $autoconf && rm -rf autom4te*.cache )
-elif find maint -name 'configure.in' -newer 'maint/configure' ; then
+elif find maint -name 'configure.in' -newer 'maint/configure' >/dev/null 2>&1 ; then
     # The above relies on the Unix find command
     (cd maint && $autoconf && rm -rf autom4te*.cache)
 fi
@@ -364,14 +354,14 @@ fi
 #
 # The following relies on the Unix find command
 if [ -s maint/simplemake ] ; then
-    if find maint -name 'simplemake.in' -newer 'maint/simplemake' ; then
+    if find maint -name 'simplemake.in' -newer 'maint/simplemake' >/dev/null 2>&1 ; then
         run_configure=yes
     fi
 else
     run_configure=yes
 fi
 if [ -s maint/genstates ] ; then 
-    if find maint -name 'genstates.in' -newer 'maint/genstates' ; then
+    if find maint -name 'genstates.in' -newer 'maint/genstates' >/dev/null 2>&1 ; then
         run_configure=yes
     fi
 else
@@ -506,12 +496,19 @@ if [ $do_build_configure = yes ] ; then
 	    if [ -d $confdbSrcDir ] ; then
                 cp -rp $confdbSrcDir confdb
                 # Remove the CVS directories
-		if test -d confdb/CVS ; then
+		if [ -d confdb/CVS ] ; then
                     (cd confdb && find . -name CVS -print | xargs rm -rf)
                 fi
             else
-                echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
-  	        exit 1
+		# Try to use scp
+                scp -rp shakey.mcs.anl.gov:$confdbSrcDir confdb
+		if [ -d confdb/CVS ] ; then
+		    (cd confdb && find . -name CVS -print | xargs rm -rf)
+                fi
+		if [ ! -d confdb ] ; then    
+                    echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
+  	            exit 1
+                fi
             fi
         elif [ -d confdb -a -d "$confdbSrcDir" -a ! -d confdb/CVS ] ; then
             # This is a copy; get an up-to-date copy.  We only do 
@@ -519,7 +516,7 @@ if [ $do_build_configure = yes ] ; then
 	    # part of the distributed version and not local.
             cp -rp $confdbSrcDir confdb
             # Remove the CVS directories
-	    if test -d confdb/CVS ; then
+	    if [ -d confdb/CVS ] ; then
                 (cd confdb && find . -name CVS -print | xargs rm -rf)
             fi
         fi
