added support for vpath

diff --git a/src/mpi/romio/configure b/src/mpi/romio/configure
--- a/src/mpi/romio/configure
+++ b/src/mpi/romio/configure
@@ -1,5 +1,6 @@
 
 
+
    
 #!/bin/sh
 # Guess values for system-dependent variables and create Makefiles.
@@ -337,10 +338,115 @@ esac
 configure_args="$*"
 
 #
+
+# Find the source files, if location was not specified.
+if test "$srcdirdefaulted" = "yes" ; then
+  srcdir=""
+  # Try the directory containing this script, then `..'.
+  prog=$0
+  confdir=`echo $prog|sed 's%/[^/][^/]*$%%'`
+  # Remove all trailing /'s 
+  confdir=`echo $confdir|sed 's%[/*]$%%'`
+  test "X$confdir" = "X$prog" && confdir=.
+  srcdir=$confdir
+  if test ! -r $srcdir/$unique_file; then
+    srcdir=..
+  fi
+fi
+if test ! -r $srcdir/$unique_file; then
+  if test x$srcdirdefaulted = xyes; then
+    echo "configure: Cannot find sources in \`${confdir}' or \`..'." 1>&2
+  else
+    echo "configure: Cannot find sources in \`${srcdir}'." 1>&2
+  fi
+  exit 1
+fi
+# Preserve a srcdir of `.' to avoid automounter screwups with pwd.
+# (and preserve ./ and .//)
+# But we can't avoid them for `..', to make subdirectories work.
+case $srcdir in
+  .|./|.//|/*|~*) ;;
+  *) srcdir=`cd $srcdir; pwd` ;; # Make relative path absolute.
+esac
+
+#
+
+
+if test -z "$ac_echo_n" ; then
+ac_echo_n=yes
+if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
+  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
+    ac_n= ac_c='
+' ac_t='	'
+  else
+    ac_n=-n ac_c= ac_t=
+  fi
+else
+  ac_n= ac_c='\c' ac_t=
+fi
+ac_echo_test=`echo foo 1>&1`
+if test -z "$ac_echo_test" ; then
+     print_error "Your sh shell does not handle the output redirection"
+     print_error "1>&1 correctly.  Configure will work around this problem,"
+     print_error "but you should report the problem to your vendor."
+fi
+
+fi
+if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo $ac_n "checking for virtual path format""... $ac_c"
+else
+echo $ac_n "checking for virtual path format""... $ac_c" 1>&1
+fi
+rm -rf conftest*
+mkdir conftestdir
+cat >conftestdir/a.c <<EOF
+A sample file
+EOF
+cat > conftest <<EOF
+all: a.o
+VPATH=.:conftestdir
+.c.o:
+	@echo \$<
+EOF
+ac_out=`$MAKE -f conftest 2>&1 | grep 'conftestdir/a.c'`
+if test -n "$ac_out" ; then 
+    if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""VPATH"
+else
+echo "$ac_t""VPATH" 1>&1
+fi
+    VPATH='VPATH=.:$(srcdir)'
+else
+    rm -f conftest
+    cat > conftest <<EOF
+all: a.o
+.PATH: . conftestdir
+.c.o:
+	@echo \$<
+EOF
+    ac_out=`$MAKE -f conftest 2>&1 | grep 'conftestdir/a.c'`
+    if test -n "$ac_out" ; then 
+        if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t"".PATH"
+else
+echo "$ac_t"".PATH" 1>&1
+fi
+        VPATH='.PATH: . $(srcdir)'
+    else
+	if test -z "$ac_echo_test" -a 1 = 1 ; then
+echo "$ac_t""neither VPATH nor .PATH works"
+else
+echo "$ac_t""neither VPATH nor .PATH works" 1>&1
+fi
+    fi
+fi
+rm -rf conftest*
+
+#
 # Check that an arch was set
 # If it wasn't set, try to guess using "util/tarch"
 #
-if test -z "$ARCH" -a -x util/tarch ; then
+if test -z "$ARCH" -a -x $srcdir/util/tarch ; then
     if test -z "$ac_echo_n" ; then
 ac_echo_n=yes
 if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
@@ -366,7 +472,7 @@ echo $ac_n "checking for architecture""... $ac_c"
 else
 echo $ac_n "checking for architecture""... $ac_c" 1>&1
 fi
-    ARCH=`./util/tarch | sed s/-/_/g`
+    ARCH=`$srcdir/util/tarch | sed s/-/_/g`
     if test -z "$ARCH" ; then
        if test -z "$ac_echo_test" -a 1 = 1 ; then
 echo "$ac_t""Unknown!"
@@ -386,7 +492,7 @@ fi
 fi
 #
 # check for valid architecture
-grep _"$ARCH"_ .config_params > /dev/null 2>&1
+grep _"$ARCH"_ $srcdir/.config_params > /dev/null 2>&1
 if test $? != 0 ; then
    echo "Unknown architecture $arch... proceeding anyway"
 fi
@@ -395,7 +501,7 @@ fi
 if test -n "$FILE_SYSTEM" ; then
    for x in $FILE_SYSTEM
    do
-      grep _"$x"_ .config_params > /dev/null 2>&1
+      grep _"$x"_ $srcdir/.config_params > /dev/null 2>&1
       if test $? != 0 ; then
          echo "Unknown file system $x... proceeding anyway"
       fi
@@ -404,7 +510,7 @@ fi
 #
 # check for valid MPI implementation
 if test -n "$MPI" ; then
-   grep _"$MPI"_mpi .config_params > /dev/null 2>&1
+   grep _"$MPI"_mpi $srcdir/.config_params > /dev/null 2>&1
    if test $? != 0 ; then
       echo "Unknown MPI implementation $MPI... proceeding anyway"
    fi
@@ -2532,7 +2638,11 @@ fi
 
    fi
 fi
-
+# Find the home directory if not specified
+if test "X$srcdir" != "X." -a -s $srcdir/mpi-io/Makefile.in ; then 
+    ROMIO_HOME_TRIAL=$srcdir
+else
+    
 ROMIO_HOME_TRIAL=$PWD
 if test "${ROMIO_HOME_TRIAL}" != "" -a -d "${ROMIO_HOME_TRIAL}" ; then 
     if test -r ${ROMIO_HOME_TRIAL}/.foo$$ ; then
@@ -2578,17 +2688,20 @@ if test -z "${ROMIO_HOME_TRIAL}" ; then
     fi
 fi
 
+fi
 echo "ROMIO home directory is $ROMIO_HOME_TRIAL"
 ROMIO_HOME=$ROMIO_HOME_TRIAL
+if test -z "$srcdir" -o "$srcdir" = "." ; then srcdir="$ROMIO_HOME" ; fi
+
 if test -z "$LIBNAME"; then
 LIBNAME="$ROMIO_HOME/lib/$ARCH/libmpio.a"
 fi
 #
-if test ! -d lib ; then 
-   mkdir lib
+if test ! -d $ROMIO_HOME/lib ; then 
+   mkdir $ROMIO_HOME/lib
 fi
-if test ! -d lib/$ARCH ; then 
-   mkdir lib/$ARCH
+if test ! -d $ROMIO_HOME/lib/$ARCH ; then 
+   mkdir $ROMIO_HOME/lib/$ARCH
 fi
 #
 if test $NOF77 = 1 ; then
@@ -2709,9 +2822,9 @@ else
 fi
 #
 if test "$MPI_INCLUDE_DIR" = "." ; then
-   ROMIO_INCLUDE="-I$ROMIO_HOME/include"
+   ROMIO_INCLUDE="-I../include"
 else 
-   ROMIO_INCLUDE="-I$ROMIO_HOME/include -I$MPI_INCLUDE_DIR"
+   ROMIO_INCLUDE="-I../include -I$MPI_INCLUDE_DIR"
 fi
 #
 TEST_LIBNAME=$LIBNAME
@@ -2808,6 +2921,8 @@ echo "setting USER_FFLAGS to $USER_FFLAGS"
 
 
 
+if test ! -d adio ; then mkdir adio ; fi
+if test ! -d mpi2-other ; then mkdir mpi2-other ; fi
 # Set default prefixes.
 if test -n "$prefix"; then
   test -z "$exec_prefix" && exec_prefix='${prefix}'
@@ -2849,9 +2964,11 @@ do
 done
 
 trap 'rm -f Makefile mpi-io/Makefile mpi2-other/info/Makefile mpi2-other/array/Makefile adio/common/Makefile test/Makefile test/misc.c test/large_file.c test/runtests util/romioinstall include/mpio.h include/mpiof.h; exit 1' 1 3 15
+VPATH='$VPATH'
 RANLIB='$RANLIB'
 CC='$CC'
 F77='$F77'
+srcdir='$srcdir'
 FILE_SYSTEM='$FILE_SYSTEM'
 CFLAGS='$CFLAGS'
 USER_CFLAGS='$USER_CFLAGS'
@@ -2905,7 +3022,6 @@ ROMIO_TCPPFLAGS='$ROMIO_TCPPFLAGS'
 ROMIO_TFFLAGS='$ROMIO_TFFLAGS'
 MPIRUN='$MPIRUN'
 LIBS='$LIBS'
-srcdir='$srcdir'
 DEFS='$DEFS'
 prefix='$prefix'
 exec_prefix='$exec_prefix'
@@ -2931,9 +3047,11 @@ for file in .. ${CONFIG_FILES}; do if test "x$file" != x..; then
   sed -e "
 $prsub
 $extrasub
+s%@VPATH@%$VPATH%g
 s%@RANLIB@%$RANLIB%g
 s%@CC@%$CC%g
 s%@F77@%$F77%g
+s%@srcdir@%$srcdir%g
 s%@FILE_SYSTEM@%$FILE_SYSTEM%g
 s%@CFLAGS@%$CFLAGS%g
 s%@USER_CFLAGS@%$USER_CFLAGS%g
@@ -2987,7 +3105,6 @@ s%@ROMIO_TCPPFLAGS@%$ROMIO_TCPPFLAGS%g
 s%@ROMIO_TFFLAGS@%$ROMIO_TFFLAGS%g
 s%@MPIRUN@%$MPIRUN%g
 s%@LIBS@%$LIBS%g
-s%@srcdir@%$srcdir%g
 s%@DEFS@%$DEFS%
 " $top_srcdir/${file}.in >> $file
 fi; done
