added weak symbols and incorporated changes suggested by Notre Dame

diff --git a/src/mpi/romio/Makefile.in b/src/mpi/romio/Makefile.in
--- a/src/mpi/romio/Makefile.in
+++ b/src/mpi/romio/Makefile.in
@@ -110,32 +110,34 @@ mpiolib:
          done
 
 profile: 
-	@dirs=`echo "$(MPIO_DIRS)"`; \
-        if test "$(BUILD_MPI_INFO)" = 1 ; then \
-            dirs=`echo "$$dirs" mpi2-other/info` ;\
-            if test "$(NOF77)" = 0 ; then\
-                dirs=`echo "$$dirs" mpi2-other/info/fortran` ;\
-            fi;\
-        fi; \
-        if test "$(BUILD_MPI_ARRAY)" = 1 ; then \
-            dirs=`echo "$$dirs" mpi2-other/array` ;\
-            if test "$(NOF77)" = 0 ; then\
-                dirs=`echo "$$dirs" mpi2-other/array/fortran` ;\
-            fi;\
-        fi; \
-        if test "$(NOF77)" = 0 ; then\
-            dirs=`echo "$$dirs" mpi-io/fortran` ;\
-        fi;\
-        for dir in $$dirs ;\
-         do \
-            echo " " ;\
-            echo building profiling interface in directory $$dir ;\
-            (cd $$dir; \
-             $(MAKE) profile MPIOPROFILE="-D__MPIO_BUILD_PROFILING";) ;\
-             if [ $$? != 0 ] ; then \
-                 echo "Make failed in directory $$dir" ; exit 1 ;\
-             fi ;\
-         done
+	@if [ "@HAS_WEAK_SYMBOLS@" = 0 ] ; then \
+           dirs=`echo "$(MPIO_DIRS)"`; \
+           if test "$(BUILD_MPI_INFO)" = 1 ; then \
+               dirs=`echo "$$dirs" mpi2-other/info` ;\
+               if test "$(NOF77)" = 0 ; then\
+                   dirs=`echo "$$dirs" mpi2-other/info/fortran` ;\
+               fi;\
+           fi; \
+           if test "$(BUILD_MPI_ARRAY)" = 1 ; then \
+               dirs=`echo "$$dirs" mpi2-other/array` ;\
+               if test "$(NOF77)" = 0 ; then\
+                   dirs=`echo "$$dirs" mpi2-other/array/fortran` ;\
+               fi;\
+           fi; \
+           if test "$(NOF77)" = 0 ; then\
+               dirs=`echo "$$dirs" mpi-io/fortran` ;\
+           fi;\
+           for dir in $$dirs ;\
+            do \
+               echo " " ;\
+               echo building profiling interface in directory $$dir ;\
+               (cd $$dir; \
+                $(MAKE) profile MPIOPROFILE="-D__MPIO_BUILD_PROFILING";) ;\
+                if [ $$? != 0 ] ; then \
+                    echo "Make failed in directory $$dir" ; exit 1 ;\
+                fi ;\
+            done \
+	fi
 
 cleanall:
 	@dirs=`echo "$(ALL_DIRS)"`; \
