Updated romio install to use mpiinstall-style CopyFile and uninstall file

diff --git a/src/mpi/romio/util/romioinstall.in b/src/mpi/romio/util/romioinstall.in
--- a/src/mpi/romio/util/romioinstall.in
+++ b/src/mpi/romio/util/romioinstall.in
@@ -7,7 +7,7 @@
 #
 #    (if you used -prefix at configure time) or,
 #
-#    make install PREFIX=/usr/local/romio  (or whatever directory you like)
+#    make install prefix=/usr/local/romio  (or whatever directory you like)
 #
 # in the top-level romio directory
 #
@@ -18,10 +18,94 @@ RANLIB=@RANLIB@
 # LAM Do we want to install or uninstall?
 WANT_INSTALL=1
 #
+# Default paths (set at configure time)
+    prefix=@prefix@
+    exec_prefix=@exec_prefix@
+    bindir=@bindir@
+    sbindir=@sbindir@
+    includedir=@includedir@
+    #sysconfdir=@sysconfdir@
+    libdir=@libdir@
+    #sharedlib_dir=@sharedlib_dir@
+    mandir=@mandir@
+    htmldir=@htmldir@
+    #datadir=@datadir@
+    docdir=@docdir@
+## Location of sources
+#top_srcdir=@top_srcdir@
+#
+# File access mode
+MODE=0664
+XMODE=0775
+replace=1
+
+# Shell procedures to copy files and create directories
+#
+# We could use install, but install is too different and too hard to 
+# test.  So here are the routines to copy file, make directories, and 
+# replace #...# and @...@ in files
+CP=cp
+#
+CopyFile() {
+if [ -z "$3" ] ; then
+    mode=$MODE
+else
+    mode=$3
+fi
+if [ -d $2 ] ; then
+    dest=$2/`basename $1`
+else
+    dest=$2
+fi
+if [ $replace = 0 -a -f $dest ] ; then
+    if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
+elif [ -d $1 ] ; then
+    echo ">>> $1 is a directory; not copied <<<"
+    errs=`expr $errs + 1`
+    if [ $failmode = "hard" ] ; then exit 1 ; fi
+elif [ ! -f $1 ] ; then 
+    echo "**File $1 does not exist (or is not a regular file)!"
+    errs=`expr $errs + 1`
+    if [ $failmode = "hard" ] ; then exit 1 ; fi
+else
+    if [ $verbose = 1 ] ; then echo "Copying $1 to $dest" ; fi
+    # We don't delete the file in the event that we are copying the
+    # file over itself (we SHOULD check for that separately, by checking 
+    # that directories are distinct)
+    #if [ -f $dest ] ; then $Show /bin/rm -f $dest ; fi
+    $Show $CP $1 $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+	echo "**Error copying file $1 to $dest **"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    else
+	echo "/bin/rm -f $dest" >> $UNINSTALLFILE
+    fi
+    $Show chmod $mode $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+	echo "**Error setting mode on file $dest**"
+        errs=`expr $errs + 1`
+        if [ $chmodefailmode = "hard" ] ; then exit $rc ; fi
+    fi
+fi
+}
+
+#
+# A version of copy file that preserves file dates
+CopyFileP() {
+    CP="$CPRP -p"
+    CopyFile $1 $2 $3
+    CP=cp
+}
+
+#
 for arg in "$@" ; do
     case "$arg" in 
         -prefix=*)
             PREFIX=`echo $arg | sed -e 's/-prefix=//'`
+	    prefix=$PREFIX
             ;;
 # LAM Added -uninstall option
         -uninstall)
@@ -33,92 +117,92 @@ for arg in "$@" ; do
             ;;
     esac
 done
-if test -z "$PREFIX" ; then
-    echo "Usage: make install PREFIX=/usr/local/romio  (or whatever directory you like)"
+if test -z "$prefix" ; then
+    echo "Usage: make install prefix=/usr/local/romio  (or whatever directory you like)"
     echo "in the top-level romio directory"
 fi
+
+# Uninstall filename
+if [ -z "$UNINSTALLFILE" ] ; then 
+    UNINSTALLFILE="$sbindir/romiouninstall"
+fi
+
 # LAM top-level switch to install or uninstall
 if test "$WANT_INSTALL" = "1"; then
-    if [ ! -d $PREFIX ] ; then
-         echo "Creating directory $PREFIX"
-         mkdir -p $PREFIX
-         chmod 755 $PREFIX
+
+# Directories
+
+# Files
+    MkDir $prefix
+
+    echo "copying directory $ROMIO_HOME/doc to $docdir"
+    MkDir $docdir
+    for file in COPYRIGHT README users-guide.ps.gz ; do
+	CopyFile $ROMIO_HOME/$file $docdir
     fi
-    echo copying $ROMIO_HOME/COPYRIGHT to $PREFIX/COPYRIGHT
-    cp $ROMIO_HOME/COPYRIGHT $PREFIX
-    chmod 644 $PREFIX/COPYRIGHT
-    echo copying directory $ROMIO_HOME/doc to $PREFIX/doc
-    cp -r $ROMIO_HOME/doc $PREFIX
-    chmod 755 $PREFIX/doc
-    chmod 644 $PREFIX/doc/README
-    chmod 644 $PREFIX/doc/users-guide.ps.gz
-    echo copying directory include to $PREFIX/include
-    if [ ! -d $PREFIX/include ] ; then
-        echo "Creating directory $PREFIX/include"
-        mkdir $PREFIX/include
-        chmod 755 $PREFIX/include
+
+    echo "copying directory include to $includedir"
+    MkDir $includedir
+    for file in include/*.h ; do
+        CopyFile $file $includedir
+    done
+
+    echo "copying directory $ROMIO_HOME/lib to $libdir"
+    #cp -r $ROMIO_HOME/lib $PREFIX
+    #chmod 755 $PREFIX/lib
+    for file in $ROMIO_HOME/lib/* ; do
+	if [ -f $file ] ; then 
+            CopyFileP $file $libdir 
+        fi
+    done
+    # Romio also copies directories in the lib directory.  
+
+    if [ -z "$mandir" ] ; then 
+	mandir=$PREFIX/man
     fi
-    cp include/*.h $PREFIX/include
-    chmod 644 $PREFIX/include/mpio.h
-    chmod 644 $PREFIX/include/mpiof.h
-    echo copying directory $ROMIO_HOME/lib to $PREFIX/lib
-    cp -r $ROMIO_HOME/lib $PREFIX
-    chmod 755 $PREFIX/lib
-    find $PREFIX/lib -type d -name "*" -exec chmod 755 {} \;
-    find $PREFIX/lib -type f -name "*" -exec chmod 644 {} \;
-    echo copying directory $ROMIO_HOME/man to $PREFIX/man
-    cp -r $ROMIO_HOME/man $PREFIX
-    chmod 755 $PREFIX/man $PREFIX/man/man3
-    chmod 644 $PREFIX/man/man3/*.3
-    echo copying directory $ROMIO_HOME/test to $PREFIX/test
-    if [ ! -d $PREFIX/test ] ; then
-        echo "Creating directory $PREFIX/test"
-        mkdir $PREFIX/test
-        chmod 755 $PREFIX/test
-    fi
-    cp -r $ROMIO_HOME/test/std $PREFIX/test
-    cp test/Makefile $PREFIX/test
-    cp test/README $PREFIX/test
-    cp test/*.c $PREFIX/test
-    cp test/*.f $PREFIX/test
-    cp test/runtests $PREFIX/test
-    chmod 755 $PREFIX/test
-    chmod 644 $PREFIX/test/*.c $PREFIX/test/*.f $PREFIX/test/README
-    chmod 755 $PREFIX/test/runtests $PREFIX/test/std
-    chmod 644 $PREFIX/test/std/*.std
-    $RANLIB $PREFIX/lib/$ARCH/libmpio.a
+    echo "copying directory $ROMIO_HOME/man to $mandir"
+    MkDir $mandir
+    MkDir $mandir/man3
+    for file in $ROMIO_HOME/man/man3/* ; do
+        CopyFile $file $mandir/man3
+    done
+
+    if [ -z "$exampledir" ] ; then exampledir=$PREFIX/examples ; fi
+    echo "copying directory $ROMIO_HOME/test to $exampledir"
+    MkDir $exampledir
+    MkDir $exampledir/std
+    for file in $ROMIO_HOME/test/std/* ; do 
+	CopyFile $file $exampledir/std
+    done
+    CopyFile test/Makefile $exampledir
+    CopyFile test/README $exampledir
+    for file in test/*.c test/*.f test/runtests ; do
+	CopyFile $file $exampledir
+    done
+    # Ranlib should not be necessary if cp -p is used
+    #$RANLIB $PREFIX/lib/$ARCH/libmpio.a
     # change the include and lib paths in Makefile in the test directory
-    echo updating paths in $PREFIX/test/Makefile
-    TMPNEWINC=-I$PREFIX/include
-    TMPNEWLIB=$PREFIX/lib/$ARCH/libmpio.a
+
+    echo "updating paths in $exampledir/Makefile"
+    TMPNEWINC=-I$includedir
+    TMPNEWLIB=$libdir/$ARCH/libmpio.a
     NEWINC=`echo $TMPNEWINC | sed 's/\//\\\\\//g'`
     NEWLIB=`echo $TMPNEWLIB | sed 's/\//\\\\\//g'`
     sed -e 5s/INCLUDE_DIR[\ ]*=\ [/a-z0-9.A-Z_-]*/INCLUDE_DIR\ =\ $NEWINC/ \
-        -e 6s/LIBS[\ ]*=\ [/a-z0-9.A-Z_-]*/LIBS\ =\ $NEWLIB/ $PREFIX/test/Makefile\
-           > $PREFIX/test/.romiotmp 
-    mv $PREFIX/test/.romiotmp $PREFIX/test/Makefile
+        -e 6s/LIBS[\ ]*=\ [/a-z0-9.A-Z_-]*/LIBS\ =\ $NEWLIB/ $exampledir/Makefile\
+           > $exampledir/.romiotmp 
+    mv $exampledir/.romiotmp $exampledir/Makefile
     
+    #
+    echo "/bin/rm -f $UNINSTALLFILE" >> $UNINSTALLFILE
+    # Add the directory removes to the UNINSTALL file
+    for dir in $dirlist ; do
+        echo "if [ -d $dir ] ; then rmdir $dir ; fi" >> $UNINSTALLFILE
+    done
 else
 
 # LAM do all the things for uninstall -- do the opposite of above.
 # This whole section is new.
-
-    echo "- removing COPYRIGHT"
-    rm -f $PREFIX/COPYRIGHT
-
-    cd $ROMIO_HOME
-    echo "- cleaning include directory"
-    for file in `ls include/*.h`; do
-	rm -f $PREFIX/$file
-    done
-
-    subdirs="doc lib man test"
-    for subdir in $subdirs; do
-	echo "- cleaning $subdir tree"
-	for file in `find $subdir -type f -print`; do
-	    rm -f $PREFIX/$file
-	done
-    done
-
+    $sbindir/romiouninstall
     echo "ROMIO uninstalled"
 fi
